#!/bin/bash

if tty -s
then
    BLACK="\[$(tput setaf 0)\]"
    RED="\[$(tput setaf 1)\]"
    GREEN="\[$(tput setaf 2)\]"
    YELLOW="\[$(tput setaf 3)\]"
    BLUE="\[$(tput setaf 4)\]"
    MAGENTA="\[$(tput setaf 5)\]"
    CYAN="\[$(tput setaf 6)\]"
    WHITE="\[$(tput setaf 7)\]"
    LIME_YELLOW="\[$(tput setaf 190)\]"
    POWDER_BLUE="\[$(tput setaf 153)\]"
    KEY_ORANGE="\[$(tput setaf 214)\]"
    BOLD="\[$(tput bold)\]"
    NORMAL="\[$(tput sgr0)\]"
    BLINK="\[$(tput blink)\]"
    REVERSE="\[$(tput smso)\]"
    UNDERLINE="\[$(tput smul)\]"

    # Disable bullshit flow control
    stty -ixon
fi

